services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MONGO_INITDB_DATABASE=production

  backend:
    build: ./backend
    container_name: backend_api
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
